project_id = "default"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public", "propuestas"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "https://sp.1hv.es"

[auth]
enabled = true
site_url = "https://sp.1hv.es"
additional_redirect_urls = ["https://sp.1hv.es", "https://sp.1hv.es/auth/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true

[auth.external.google]
enabled = true
client_id = "1050921918079-li1hsithbefe4bpunlntab2dl4qcck9m.apps.googleusercontent.com"
secret = "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"
redirect_uri = "https://sp.1hv.es/auth/callback"

[inbucket]
enabled = false

[storage]
enabled = true

[analytics]
enabled = false
